test-cookbook3:
  stage: test
  script:
    - cd cookbook3
    - bundle install
    - rails db:migrate RAILS_ENV=test
    
  only:
    - cookbook3

deploy-cookbook3:
  stage: deploy
  script:
    - rsync -arv ./cookbook3 /
    - cd /cookbook3
    - bundle install
    - rails db:migrate
    - sv restart cookbook3
  only:
  - cookbook3 

test-blog4:
  stage: test
  script:
    - cd blog4
    - bundle install
    - rails db:migrate RAILS_ENV=test
    # - PARALLEL_WORKERS=1 rails test
  only:
    - blog4

deploy-blog4:
  stage: deploy
  script:
    - rsync -arv ./blog4 /
    - cd /blog4
    - bundle install
    - rails db:migrate
    - sv restart blog4
  only:
    - blog4

test-project:
  stage: test
  script:
    - cd project
    - bundle install
    - rails db:migrate RAILS_ENV=test
    #- PARALLEL_WORKERS=1 rails test
  only:
    - project

deploy-project:
  stage: deploy
  script:
    - rsync -arv --delete  --exclude="*.sqlite3" ./project /
    - cd /project
    - bundle install
    - rails db:migrate
    - sv restart project
  only:
    - project
